# Change these first
owner: quakeworldnu
repo: status.quakeworld.nu

sites:
  - name: QuakeWorld.nu
    url: https://www.quakeworld.nu

  - name: QuakeWorld Wiki
    url: https://www.quakeworld.nu/wiki/Overview

  - name: QuakeWorld GFX
    url: https://gfx.quakeworld.nu

  - name: QuakeWorld Hub
    url: https://hub.quakeworld.nu

  - name: QuakeWorld Hub API
    url: https://hubapi.quakeworld.nu/v2/servers/mvdsv

  - name: QuakeWorld Duel Ranks
    url: https://www.qwranks.com

  - name: QuakeWorld Duel Ranks API
    url: https://backend.qwranks.com/matches/0

  - name: QHLAN.org
    url: https://www.qhlan.org

status-website:
  cname: status.quakeworld.nu
  logoUrl: https://www.quakeworld.nu/images/logo.gif
  name: QuakeWorld Status

#  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
#  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
#  navbar:
#    - title: Status
#      href: /
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
